### ISSUE TITLE
TypeError: settings.import/parsers[parser].forEach is not a function

### ISSUE THREAD

**Issue by epkatz** [benmosher/eslint-plugin-import#1149]
When running the eslint plugin for vscode I'm getting the following error with my eslint setup. Any help would be greatly appreciated. 

```
[Info  - 15:47:19] ESLint server is running.
[Info  - 15:47:21] ESLint library loaded from: /Users/epkatz/Src/wonder/packages/api/node_modules/eslint/lib/api.js
[Error - 15:47:32] ESLint stack trace:
[Error - 15:47:32] TypeError: settings.import/parsers[parser].forEach is not a function
    at makeValidExtensionSet (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint-module-utils/ignore.js:28:10)
    at validExtensions (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint-module-utils/ignore.js:16:15)
    at hasValidExtension (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint-module-utils/ignore.js:54:10)
    at Function.ExportMap.for (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint-plugin-import/lib/ExportMap.js:315:38)
    at Function.ExportMap.get (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint-plugin-import/lib/ExportMap.js:292:23)
    at checkDefault (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint-plugin-import/lib/rules/no-named-as-default.js:31:41)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at CommentEventGenerator.enterNode (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Traverser.enter (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint/lib/eslint.js:929:36)
    at Traverser.__execute (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Traverser.traverse (/Users/epkatz/Src/wonder/packages/api/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
```

This is my .eslintrc.json file
```
{
  "rules": {
    "prettier/prettier": "error",
    "import/prefer-default-export": "off",
    "no-extra-parens": ["error", "all", { "nestedBinaryExpressions": false }],
    "no-param-reassign": [2, { "props": false }],
    "no-restricted-syntax": [
      "error",
      "ForInStatement",
      "LabeledStatement",
      "WithStatement"
    ],
    "no-mixed-operators": ["error", {"allowSamePrecedence": true}],
    "no-underscore-dangle": ["error", { "allow": ["_id"] }],
    "jest/no-disabled-tests": "warn",
    "jest/no-focused-tests": "error",
    "jest/no-identical-title": "error",
    "jest/valid-expect": "error",
    "import/extensions": ["error", { "ts": "never", "js": "never" }]
  },
  "ecmaFeatures": {
    "modules": true
  },
  "settings": {
    "import/resolver": {
      "node": true,
      "eslint-import-resolver-typescript": true
    },
    "import/parsers": {
      "typescript-eslint-parser": [".ts", ".tsx"],
      "babel-eslint": [".js", ".jsx"],
      "rules": {
        "no-undef": "off"
      }
    }
  },
  "env": {
    "es6": true,
    "node": true,
    "jest/globals": true
  },
  "plugins": [
    "typescript",
    "prettier",
    "jest"
  ],
  "extends": [
    "airbnb/base",
    "plugin:jest/recommended",
    "plugin:prettier/recommended",
    "prettier"
  ],
  "parser": "typescript-eslint-parser"
}
```

I'm using version 2.13.0

**Comment by epkatz** [comment]
It's fixed when I remove
```
"rules": {
        "no-undef": "off"
      }
```
but I think that's valid?

**Comment by ljharb** [comment]
I don't know why it would be valid - "rules" is a top-level key; it can't go inside "settings".

**Comment by ljharb** [comment]
I've pushed up a fix that throws a clearer error message.
