### ISSUE TITLE
Why use packageDir to join configPath but not the directory where eslint is configured ?

### ISSUE THREAD

**Issue by cytle** [benmosher/eslint-plugin-import#1158]
When the path is not an absolute path, `eslint-import-resolver-webpack` will use packageDir to join configPath. As shown in the following code.

```js
// https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/webpack/index.js#L342-L344
if (!path.isAbsolute(configPath)) {
  configPath = path.join(packageDir, configPath)
}
```

If there is a [project](https://github.com/cytle/eslint-import-demo) with the following structure, an exception will be thrown when I execute the following command.

```txt
.
├── README.md
├── package.json
├── src
│   └── storage
│       ├── index.js
│       └── package.json
├── utils
│   └── a.js
├── .eslintrc.js
└── webpack.config.js
```

```bash
npx eslint src/storage/index.js
```

```txt
Error resolving webpackConfig { Error: Cannot find module '/Users/xsp/src/js/eslint-import-demo/src/storage/webpack.config.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.exports.resolve (/Users/xsp/src/js/eslint-import-demo/node_modules/eslint-import-resolver-webpack/index.js:69:27)
    at v2 (/Users/xsp/src/js/eslint-import-demo/node_modules/eslint-module-utils/resolve.js:94:23)
    at withResolver (/Users/xsp/src/js/eslint-import-demo/node_modules/eslint-module-utils/resolve.js:99:16)
    at fullResolve (/Users/xsp/src/js/eslint-import-demo/node_modules/eslint-module-utils/resolve.js:116:22)
    at relative (/Users/xsp/src/js/eslint-import-demo/node_modules/eslint-module-utils/resolve.js:61:10)
    at resolve (/Users/xsp/src/js/eslint-import-demo/node_modules/eslint-module-utils/resolve.js:180:12) code: 'MODULE_NOT_FOUND' }
```

demo: https://github.com/cytle/eslint-import-demo

**Comment by w0rp** [comment]
I get reports about this in ALE now and then, and there's no reliable way for ALE to determine which directory to use as the correct one. You should add an option so people can configure the package directory relative to the configuration file, and then you'll be able to run ESLint from any directory and get the correct results.

**Comment by w0rp** [comment]
ALE is one of the most popular Vim plugins for running linters.

The problem is, how do you define "project root?" ESLint is designed so you can give it `--stdin-filename ... --stdin`, and then you can check files via stdin with a filename hint so it can figure out where the ESLint configuration file is, and so on.

If your plugin also requires running ESLint from a particular directory, that means that every editor or editor plugin which integrates with ESLint also has to separately implement logic for discovering where the project root for a file is. I suppose you could assume it's the directory where `package.json` is, and that will be true for most projects.

I'd rather not implement something like that, and I'd rather the ESLint plugin could figure it out like ESLint itself does. If you get it right here, then it will work for Vim, VSCode, Emacs, etc.

What I think would be better would be implementing better discovery of where the project root is, and then you won't have to care what the working directory is, less configuration will be needed, and editor plugins won't have to implement anything special to get this plugin to work.

**Comment by ljharb** [comment]
With javascript? it's where the closest package.json is, yes.

**Comment by w0rp** [comment]
Sounds like this plugin could fix the issue by working out paths relative to that directory instead of the working directory. The working directory could be a fallback option when no package.json file can be found.

**Comment by archSeer** [comment]
With typescript, what they do is search backwards up the directory tree until they find a `tsconfig` file. Maybe this plugin work in a similar way. My issue was that I had a monorepo, and the javascript code was under <root>/ui, but the linting was being ran from <root>, hence missing the eslint settings.
