### ISSUE TITLE
eslint-import-resolver-webpack unable to read ES6 webpack configs when using babel v 7

### ISSUE THREAD

**Issue by comatory** [benmosher/eslint-plugin-import#1267]
I'm trying to pinpoint the root cause and I think it boils down to this resolver plugin. It still could be some issue with my babel setup however I thought I try posting this. In my project I recently upgraded to babel version 7. When I run eslint I first get an error like this:

```
Error resolving webpackConfig { Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

...

    at fullResolve (/Users/.../Projects/.../node_modules/eslint-module-utils/resolve.js:116:22)
    at Function.relative (/Users/.../Projects/.../node_modules/eslint-module-utils/resolve.js:61:10)
    at remotePath (/Users/.../Projects/.../node_modules/eslint-plugin-import/lib/ExportMap.js:369:20)
```

After some googling I found that this issue can be resolved by adding this field to my `package.json`:

```
resolutions: {
    "babel-core": "7.0.0-bridge.0"
}
```

Then it seems that my webpack config file cannot be loaded via `eslint-import-resolver-webpack` :

```
Error resolving webpackConfig /Users/.../Projects/.../config/webpack-js.config.babel.js:1
(function (exports, require, module, __filename, __dirname) { import path from 'path'
                                                                     ^^^^

SyntaxError: Unexpected identifier

...
```

The settings for the resolver in my `.eslintrc` looks like this:

```
    "import/resolver": {
      "webpack": {
        "config": "config/webpack-js.config.babel.js"
      }
    },
```

When I remove this setting from the `.eslintrc` file, the eslint runs fine but obviously gives me import resolution errors. I have tried to transpile the config files to ES2015 but this causes the node time out and run of memory (Heap allocation error).

My `package.json` has this in it

```
"@babel/plugin-transform-modules-commonjs": "^7.2.0",
"@babel/polyfill": "^7.0.0",
 "@babel/cli": "^7.0.0",
"@babel/core": "^7.0.0",
"@babel/plugin-proposal-class-properties": "^7.0.0",
"@babel/plugin-proposal-decorators": "^7.0.0",
"@babel/plugin-proposal-do-expressions": "^7.0.0",
"@babel/plugin-proposal-export-default-from": "^7.0.0",
"@babel/plugin-proposal-export-namespace-from": "^7.0.0",
"@babel/plugin-proposal-function-bind": "^7.0.0",
"@babel/plugin-proposal-function-sent": "^7.0.0",
"@babel/plugin-proposal-json-strings": "^7.0.0",
"@babel/plugin-proposal-logical-assignment-operators": "^7.0.0",
"@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0",
"@babel/plugin-proposal-numeric-separator": "^7.0.0",
"@babel/plugin-proposal-optional-chaining": "^7.0.0",
"@babel/plugin-proposal-pipeline-operator": "^7.0.0",
"@babel/plugin-proposal-throw-expressions": "^7.0.0",
"@babel/plugin-syntax-dynamic-import": "^7.0.0",
"@babel/plugin-syntax-import-meta": "^7.0.0",
"@babel/plugin-transform-flow-strip-types": "^7.0.0",
"@babel/preset-env": "^7.0.0",
"@babel/preset-flow": "^7.0.0",
"@babel/preset-react": "^7.0.0",
"@babel/register": "^7.0.0",
...
"babel-core": "^7.0.0-bridge.0",
"babel-eslint": "^10.0.0",
"babel-jest": "^23.4.2",
"babel-loader": "^8.0.0",
"babel-plugin-add-module-exports": "^0.2.1",
"babel-plugin-dynamic-import-node": "^1.2.0",
"babel-plugin-react-transform": "^2.0.2",
"babel-plugin-transform-builtin-extend": "^1.1.2",
...
"eslint": "~5.12.1",
"eslint-config-airbnb": "~17.1.0",
"eslint-import-resolver-webpack": "^0.11.0",
"eslint-plugin-babel": "~5.3.0",
"eslint-plugin-change-listeners": "^0.0.3",
"eslint-plugin-flowtype": "^3.2.1",
"eslint-plugin-import": "~2.15.0",
"eslint-plugin-jest": "^22.1.3",
"eslint-plugin-jsx-a11y": "~6.1.2",
"eslint-plugin-mutation": "^1.0.0",
"eslint-plugin-react": "~7.12.4",
"eslint-plugin-react-props-in-state": "^1.0.5",
"eslint-plugin-standard": "~4.0.0",
```

**Comment by comatory** [comment]
Also further information that I've gathered is, if I don't use eslint v 5 and use this in my `package.json`

```
    "eslint": "~4.19.1",
    "eslint-config-airbnb": "~15.1.0",
    "eslint-import-resolver-webpack": "^0.10.0",
    "eslint-plugin-babel": "~4.1.2",
    "eslint-plugin-change-listeners": "^0.0.3",
    "eslint-plugin-flowtype": "^2.47.1",
    "eslint-plugin-import": "~2.12.0",
    "eslint-plugin-jest": "^21.17.0",
    "eslint-plugin-jsx-a11y": "~5.1.1",
    "eslint-plugin-mutation": "^1.0.0",
    "eslint-plugin-react": "~7.8.2",
    "eslint-plugin-react-props-in-state": "^1.0.5",
    "eslint-plugin-standard": "~2.0.0"
```

I'm able to run eslint (with 1 error though) on transpiled webpack config files, so that's something...

**Comment by edwining01** [comment]
# Hot fix

This is my work around.

Run

```sh
npx babel webpack.config.babel.js --out-file webpack.config.build.js
```

The config settings in file `.eslintrc`:

```js
{
  {
    "settings": {
      "import/resolver": {
        "webpack": {
          "config": "webpack-js.config.build.js"
        }
      }
    }
  }
}
```

Done.

**Comment by comatory** [comment]
@edwining01 Not a solution but a workaround. Also, in my original post I wrote:

> I have tried to transpile the config files to ES2015 but this causes the node time out and run of memory (Heap allocation error).

So yeah, that doesn't solve anything for me unfortunately :(

**Comment by jneuendorf** [comment]
@comatory Maybe increasing the heap size with `node --max-old-space-size=4096 ...` while transpilation makes the workaround work 😕

**Comment by comatory** [comment]
Did not find solution for this. Closing.
