### ISSUE TITLE
bundledDependencies validation error

### ISSUE THREAD

**Issue by frontendmonster** [benmosher/eslint-plugin-import#1497]
**.eslintrc.json**
```json
"import/no-extraneous-dependencies": ["warn", { "bundledDependencies": false }]
```
**$ eslint .**
```
Error: .eslintrc.json:
  Configuration for rule "import/no-extraneous-dependencies" is invalid:
  Value {"bundledDependencies":false} should NOT have additional properties.

    at validateRuleOptions (/home/skill/northcamp/dev/app/smartsept/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /home/skill/northcamp/dev/app/smartsept/node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/home/skill/northcamp/dev/app/smartsept/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/home/skill/northcamp/dev/app/smartsept/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/home/skill/northcamp/dev/app/smartsept/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:392:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/home/skill/northcamp/dev/app/smartsept/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:248:21)
    at FileEnumerator._iterateFilesRecursive (/home/skill/northcamp/dev/app/smartsept/node_modules/eslint/lib/cli-engine/file-enumerator.js:400:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/home/skill/northcamp/dev/app/smartsept/node_modules/eslint/lib/cli-engine/file-enumerator.js:254:49)
```

**eslint version: 6.5.1**

**Comment by ljharb** [comment]
As you can see [here](https://github.com/benmosher/eslint-plugin-import/blob/e62011f2facc2a50206f32abb496fb7a0f774ba4/CHANGELOG.md#added), bundled deps support is not yet released.
