### ISSUE TITLE
Error resolving webpackConfig { Error: Cannot find module 'webpack/package.json'

### ISSUE THREAD

**Issue by per0w** [benmosher/eslint-plugin-import#1523]
Hello. Can you please help me with issue.
I Use vscode and vscode-eslint extension. 

Plugin not working for me, i getting the message: 

`Error resolving webpackConfig { Error: Cannot find module 'webpack/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at Object.<anonymous> (project/node_modules/svg-sprite-loader/lib/utils/get-webpack-version.js:2:37)
    at Object.<anonymous> (project/node_modules/svg-sprite-loader/lib/utils/get-webpack-version.js:19:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (project/node_modules/svg-sprite-loader/lib/utils/get-module-chunk.js:1:179)
    at Object.<anonymous> (project/node_modules/svg-sprite-loader/lib/utils/get-module-chunk.js:37:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10) code: 'MODULE_NOT_FOUND' }
`

**Comment by ljharb** [comment]
What happens on the command line?

**Comment by CinKon** [comment]
Got the same error. CLI works just fine, VSCode ESLint complains...

```bash

Error resolving webpackConfig Error: Cannot find module 'webpack/package.json'
Require stack:
- /Users/lars.eichler/.vscode/extensions/dbaeumer.vscode-eslint-1.9.1/server/out/eslintServer.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at Object.require (/Users/lars.eichler/Documents/htdocs/simplicity/WWW/spryker-simplicity/assets/node_modules/svg-sprite-loader/lib/utils/get-webpack-version.js:2:37)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Module._compile (/Users/lars.eichler/Documents/htdocs/simplicity/WWW/spryker-simplicity/assets/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Object.newLoader [as .js] (/Users/lars.eichler/Documents/htdocs/simplicity/WWW/spryker-simplicity/assets/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.require (/Users/lars.eichler/Documents/htdocs/simplicity/WWW/spryker-simplicity/assets/node_modules/svg-sprite-loader/lib/utils/get-module-chunk.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Module._compile (/Users/lars.eichler/Documents/htdocs/simplicity/WWW/spryker-simplicity/assets/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Object.newLoader [as .js] (/Users/lars.eichler/Documents/htdocs/simplicity/WWW/spryker-simplicity/assets/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.require (/Users/lars.eichler/Documents/htdocs/simplicity/WWW/spryker-simplicity/assets/node_modules/svg-sprite-loader/lib/utils/index.js:6:33) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/lars.eichler/.vscode/extensions/dbaeumer.vscode-eslint-1.9.1/server/out/eslintServer.js'
  ]
}
```

**Comment by ljharb** [comment]
If the CLI works, then it's vscode's bug and you'll need to file an issue with them directly.
