### ISSUE TITLE
New release supporting ESLint 7

### ISSUE THREAD

**Issue by stof** [benmosher/eslint-plugin-import#1772]
I saw that https://github.com/benmosher/eslint-plugin-import/commit/6a110dd16a7fd775f08601054bf14ffd503eea7b marked ESLint 7 as officially supported. It would be great if a new version could be released with that change.

**Comment by dimitropoulos** [comment]
to add to that: typescript-eslint 3.0.0 [just released](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0) (with eslint 7 support) and also there are other plugins (or, at least [this one](https://github.com/dangreenisrael/eslint-plugin-jest-formatting/pull/89) that I use) that are waiting on eslint-plugin-import to release before they release.

**Comment by timelf123** [comment]
Is there anything else besides cutting a release that needs to go into 3.0.0?

**Comment by ljharb** [comment]
It’s not major, it’s minor, so it’ll be v2.21.0.

**Comment by echavaillaz** [comment]
And also allow eslint 7.1
Thanks

**Comment by silkfire** [comment]
@ljharb Are we there yet?

**Comment by ljharb** [comment]
Released.

**Comment by hamstercat** [comment]
The new release requires eslint ^7.2, but it's not working with any of the projects that currently uses eslint.

```
Oops! Something went wrong! :(

ESLint: 7.2.0

TypeError: Cannot read property 'value' of null
Occurred while linting /Users/mathieu/Code/pokemon-tcg/packages/client-server/src/commands/command.ts:4
    at ExportNamedDeclaration (/Users/mathieu/Code/pokemon-tcg/node_modules/eslint-plugin-import/lib/rules/no-internal-modules.js:111:44)
    at /Users/mathieu/Code/pokemon-tcg/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/mathieu/Code/pokemon-tcg/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/mathieu/Code/pokemon-tcg/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/mathieu/Code/pokemon-tcg/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/mathieu/Code/pokemon-tcg/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/mathieu/Code/pokemon-tcg/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:635:23)
    at /Users/mathieu/Code/pokemon-tcg/node_modules/eslint/lib/linter/linter.js:949:32
    at Array.forEach (<anonymous>)
```
