### ISSUE TITLE
[regression] `export * from 'typescript/lib/typescript.d` throws after `2.19.0`

### ISSUE THREAD

**Issue by JounQin** [benmosher/eslint-plugin-import#1801]
related: https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/47

Minimal reproduction:

```ts
// test.ts
export * from 'typescript/lib/typescript.d'
```

```yml
# .eslint.yml
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - plugin:import/errors
  - plugin:import/typescript
```

run: `eslint test.ts`

error log:

```log
TypeError: Cannot read property 'type' of null
Occurred while linting /workspace/eslint-import-resolver-typescript-repro/src.ts:1
    at /workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:569:30
    at Array.forEach (<anonymous>)
    at /workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:565:32
    at Array.forEach (<anonymous>)
    at /workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:563:19
    at Array.forEach (<anonymous>)
    at Function.ExportMap.parse (/workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:477:12)
    at Function.ExportMap.for (/workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:361:25)
    at Function.ExportMap.get (/workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:316:23)
    at processBodyStatement (/workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/rules/namespace.js:67:47)
```

After downgrading to `~2.18.2`, there will be no error any more.

**Comment by ljharb** [comment]
If it's throwing from inside the resolver, that's a bug you'll need to file on the resolver, which is a different project.

cc @alexgorbatchev

**Comment by JounQin** [comment]
@ljharb Not at all. There's no resolver used in my reproduction.

The related issue throws because the resolver resolves `typescript.d.ts` correctly instead of `typescript.js`.

**Comment by ljharb** [comment]
Hmm, I did misunderstand the stack trace - but the resolver is still the typescript resolver, which is a different package.

What's the exact stack trace on v2.20.2, the latest version?

**Comment by JounQin** [comment]
@ljharb All versions after `v2.19.0`.

**Comment by ljharb** [comment]
Right, but i need the file and line number on v2.20.2.

**Comment by JounQin** [comment]
> What's the exact stack trace on v2.20.2, the latest version?

Yes, I tested it with latest version.

**Comment by ljharb** [comment]
Test seems to pass on latest master.

**Comment by JounQin** [comment]
@ljharb I try to build latest `eslint-plugin-import` from master branch manually, but the error is still there.

```log
$ /Users/JounQin/Workspaces/Local/eslint-import-issue/node_modules/.bin/eslint test.ts

Oops! Something went wrong! :(

ESLint: 7.2.0

TypeError: Cannot read property 'type' of null
Occurred while linting /Users/JounQin/Workspaces/Local/eslint-import-issue/test.ts:1
    at /Users/JounQin/Workspaces/Local/eslint-plugin-import/lib/ExportMap.js:616:33
    at Array.forEach (<anonymous>)
    at /Users/JounQin/Workspaces/Local/eslint-plugin-import/lib/ExportMap.js:611:28
    at Array.forEach (<anonymous>)
    at /Users/JounQin/Workspaces/Local/eslint-plugin-import/lib/ExportMap.js:606:21
    at Array.forEach (<anonymous>)
    at Function.ExportMap.parse (/Users/JounQin/Workspaces/Local/eslint-plugin-import/lib/ExportMap.js:501:12)
    at Function.ExportMap.for (/Users/JounQin/Workspaces/Local/eslint-plugin-import/lib/ExportMap.js:369:25)
    at Function.ExportMap.get (/Users/JounQin/Workspaces/Local/eslint-plugin-import/lib/ExportMap.js:324:23)
    at ExportAllDeclaration (/Users/JounQin/Workspaces/Local/eslint-plugin-import/lib/rules/export.js:125:51)
```

**Comment by JounQin** [comment]
@ljharb The minimal reproduction would be like following:

```ts
// file1.ts
declare namespace ts {
  const x: string;
  export { x };
}

export = ts;
```

```ts
// file2.ts
export * from './file1.ts'
```

run `eslint file2.ts`

I print `moduleBlockNode` at https://github.com/benmosher/eslint-plugin-import/blob/master/src/ExportMap.js#L593, it is:

```json
{
  "type": "ExportNamedDeclaration",
  "source": null,
  "specifiers": [
    {
      "type": "ExportSpecifier",
      "local": {
        "type": "Identifier",
        "name": "x",
        "range": [
          53,
          54
        ],
        "loc": {
          "start": {
            "line": 3,
            "column": 11
          },
          "end": {
            "line": 3,
            "column": 12
          }
        }
      },
      "exported": {
        "type": "Identifier",
        "name": "x",
        "range": [
          53,
          54
        ],
        "loc": {
          "start": {
            "line": 3,
            "column": 11
          },
          "end": {
            "line": 3,
            "column": 12
          }
        }
      },
      "range": [
        53,
        54
      ],
      "loc": {
        "start": {
          "line": 3,
          "column": 11
        },
        "end": {
          "line": 3,
          "column": 12
        }
      }
    }
  ],
  "exportKind": "value",
  "declaration": null,
  "range": [
    44,
    57
  ],
  "loc": {
    "start": {
      "line": 3,
      "column": 2
    },
    "end": {
      "line": 3,
      "column": 15
    }
  }
}
```

**Comment by ljharb** [comment]
Thank you, got a properly failing test case with a proper fix :-)
