### ISSUE TITLE
'order ' rule breaks v2.21.1 - TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by wentjun** [benmosher/eslint-plugin-import#1808]
I'm currently on the latest version of `eslint-plugin-import` (`2.21.1`), and it seems to be breaking my linting stage for some reason. 

```
TypeError: Cannot read property 'indexOf' of null
Occurred while linting/index.ts:40
    at isAbsolute (/node_modules/eslint-plugin-import/lib/core/importType.js:48:15)
    at typeTest (/node_modules/eslint-plugin-import/lib/core/importType.js:117:7)
    at resolveImportType (/node_modules/eslint-plugin-import/lib/core/importType.js:149:10)
    at computeRank (/node_modules/eslint-plugin-import/lib/rules/order.js:315:44)
    at registerNode (/node_modules/eslint-plugin-import/lib/rules/order.js:331:16)
    at handleImports (/node_modules/eslint-plugin-import/lib/rules/order.js:598:9)
    at /node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/node_modules/eslint/lib/linter/node-event-generator.js:254:26)

```

Can't see how this particular line will go wrong, unless there are any breaking changes in that rule:

`  export import CreateSomething = _CreateSomething;
`

I didn't face any of such issues on the previous minor version. If there are any new changes to the rule, it should be reflected as part of the linting result, rather than throwing an error halfway.

**Comment by ljharb** [comment]
export import? I’m not familiar with that syntax.

**Comment by ljharb** [comment]
Looks like it's this: https://stackoverflow.com/a/30714301/632724 but that suggests it should be `export import Something = require('something else')`, and not `= _CreateSomething`.

Either way, fix incoming.

**Comment by gbuchthal** [comment]
Looks like this fix isn't actually showing up in the release (2.21.1). Any idea when the release will include this change?

**Comment by wentjun** [comment]
@gbuchthal this happens in the latest release(2.21.1), thus the fix will probably only be fixed in the next patch.

**Comment by ljharb** [comment]
Indeed; this fix is not yet released.
