### ISSUE TITLE
Node must be provided when reporting error if location is not provided idk why and its messing up my workflow

### ISSUE THREAD

**Issue by CalebDelbridge** [benmosher/eslint-plugin-import#1827]
This happens on random and most of the times the error is not current it also happens top pop up when I'm just typing code

Full-stack error
```
AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided
    at assertValidNodeInfo (/usr/local/lib/node_modules/eslint/lib/linter/report-translator.js:98:9)
    at /usr/local/lib/node_modules/eslint/lib/linter/report-translator.js:311:9
    at Object.report (/usr/local/lib/node_modules/eslint/lib/linter/linter.js:917:41)
    at Program (/Users/Caleb/Desktop/Barnabus-development/main-bot/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:265:23)
    at /usr/local/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
```
All my dev dependencies 
```
    "eslint": "^7.2.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-prettier": "^3.1.4",
    "prettier": "^2.0.5"
```

**Comment by ljharb** [comment]
The stack trace says it's coming from `eslint-plugin-prettier`, which isn't this plugin/repo:
```
at Program (/Users/Caleb/Desktop/Barnabus-development/main-bot/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:265:23)
```

**Comment by CalebDelbridge** [comment]
@ljharb I see thank you I'll go to that repo and report it there
