### ISSUE TITLE
 Error: Cannot find module './configs/webpack.config.eslint.js'

### ISSUE THREAD

**Issue by doublethinkio** [benmosher/eslint-plugin-import#1865]
Steps to reproduce the problem：

1. 
```
git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name
cd your-project-name
yarn
```

2. 
```bash
$ yarn lint
yarn run v1.22.4
$ cross-env NODE_ENV=development eslint . --cache --ext .js,.jsx,.ts,.tsx
O:\git.workspace\electron.workspace\react-electron-boilerplate\configs\webpack.config.eslint.js

Oops! Something went wrong! :(

ESLint: 7.5.0

Error: Cannot read config file: O:\git.workspace\electron.workspace\.eslintrc.js
Error: Cannot find module './configs/webpack.config.eslint.js'
Require stack:
- O:\git.workspace\electron.workspace\.eslintrc.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\cli-engine\config-array-factory.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\cli-engine\cli-engine.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\eslint\eslint.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\eslint\index.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\cli.js
- O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\bin\eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.resolve (O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\v8-compile-cache\v8-compile-cache.js:166:23)
    at Object.<anonymous> (O:\git.workspace\electron.workspace\.eslintrc.js:3:22)
    at Module._compile (O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at module.exports (O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\import-fresh\index.js:31:59)
    at loadJSConfigFile (O:\git.workspace\electron.workspace\react-electron-boilerplate\node_modules\eslint\lib\cli-engine\config-array-factory.js:218:16)error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

**Comment by ljharb** [comment]
https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/configs/webpack.config.eslint.js is certainly there - and https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/.eslintrc.js#L19 seems ok too.

When I run your repro steps, everything passes for me.

**Comment by ljharb** [comment]
What version of node are you using?

**Comment by doublethinkio** [comment]
> What version of node are you using?

I tried Node V10.22.0 and the latest long-term support version 12.18.3

**Comment by doublethinkio** [comment]
> https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/configs/webpack.config.eslint.js is certainly there - and https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/.eslintrc.js#L19 seems ok too.
> 
> When I run your repro steps, everything passes for me.

You are right. 
I found another.eslintrc.js under the same sibling of the project root.
![image](https://user-images.githubusercontent.com/24669431/89123031-d5aeb600-d4fe-11ea-9db0-42ce73bf8d30.png)
