### ISSUE TITLE
Error: Cannot find module 'eslint-config-airbnb/base' from '/usr/lib/node_modules'

### ISSUE THREAD

**Issue by segmentationfaulter** [benmosher/eslint-plugin-import#201]
I am using vim's syntactic plugin, the plugin was not working with airbnb's `.eslintrc`, to investigate the issue I tried linting my file from command line by issuing the command `$ eslint app.js`, it gave the error mentioned in the subject. I am pasting the stack trace here

> Referenced from: /home/saqib/blog/.eslintrc
    at Function.module.exports [as sync] (/usr/lib/node_modules/eslint/node_modules/resolve/lib/sync.js:33:11)
    at resolve (/usr/lib/node_modules/eslint/lib/config/config-file.js:417:38)
    at load (/usr/lib/node_modules/eslint/lib/config/config-file.js:436:24)
    at /usr/lib/node_modules/eslint/lib/config/config-file.js:355:36
    at Array.reduceRight (native)
    at applyExtends (/usr/lib/node_modules/eslint/lib/config/config-file.js:338:28)
    at Object.load (/usr/lib/node_modules/eslint/lib/config/config-file.js:464:22)
    at loadConfig (/usr/lib/node_modules/eslint/lib/config.js:67:33)
    at getLocalConfig (/usr/lib/node_modules/eslint/lib/config.js:129:23)
    at Config.getConfig (/usr/lib/node_modules/eslint/lib/config.js:222:22)

**Comment by benmosher** [comment]
I have a coworker who has had to do some gymnastics to get syntactic working as well. 
I suspect one or both of eslint and the plugin are not in the same package area.
`npm -g list | grep eslint` vs `cd /home/saqib/blog && npm list | grep eslint`?

**Comment by xl-y** [comment]
I am encountering this problem.How did you solve it?@segmentationfaulter

**Comment by segmentationfaulter** [comment]
@xl-y still could not solve it.

**Comment by benmosher** [comment]
I think you probably need to globally install any ESLint plugins.

Try running `npm install -g eslint-config-airbnb` in a terminal.
