### ISSUE TITLE
newline-after-import will break when there is an export right after an import

### ISSUE THREAD

**Issue by carlosnakane** [benmosher/eslint-plugin-import#2063]
Hello,
We found a bug when exporting right after importing like this:

```
import stub from './stub';

export {
    stub
}
```

It throws:

```
Oops! Something went wrong! :(

ESLint: 7.26.0

TypeError: Cannot read property 'type' of null
Occurred while linting C:\Users\carlos.nakane\_repos\_temp\tp\eslint-plugin-import-bug-report\src\index.ts:1
    at isExportNameClass (C:\Users\carlos.nakane\_repos\_temp\tp\eslint-plugin-import-bug-report\node_modules\eslint-plugin-import\lib\rules\newline-after-import.js:51:69)
    at checkForNewLine (C:\Users\carlos.nakane\_repos\_temp\tp\eslint-plugin-import-bug-report\node_modules\eslint-plugin-import\lib\rules\newline-after-import.js:79:45)
    at checkImport (C:\Users\carlos.nakane\_repos\_temp\tp\eslint-plugin-import-bug-report\node_modules\eslint-plugin-import\lib\rules\newline-after-import.js:133:9)
    at C:\Users\carlos.nakane\_repos\_temp\tp\eslint-plugin-import-bug-report\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\carlos.nakane\_repos\_temp\tp\eslint-plugin-import-bug-report\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\carlos.nakane\_repos\_temp\tp\eslint-plugin-import-bug-report\node_modules\eslint\lib\linter\node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (C:\Users\carlos.nakane\_repos\_temp\tp\eslint-plugin-import-bug-report\node_modules\eslint\lib\linter\node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (C:\Users\carlos.nakane\_repos\_temp\tp\eslint-plugin-import-bug-report\node_modules\eslint\lib\linter\node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (C:\Users\carlos.nakane\_repos\_temp\tp\eslint-plugin-import-bug-report\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:711:23)
```

The problem occurs when using eslint-import-plugin 2.23.0
It was fine when I was using 2.22.1

I created a repo to reproduce the problem https://github.com/carlosnakane/eslint-plugin-import-bug-report

**Comment by annguyen-dev** [comment]
The issue is still remaining. Why was it closed?

**Comment by ljharb** [comment]
@annguyen-dev issues everywhere on GitHub are closed when the fix lands, not when the fix is released. The next release - which will be soon - will contain the fix.

**Comment by larshp** [comment]
yea, also still experiencing the issue

**Comment by targos** [comment]
The last release on npm (2.23.1) doesn't contain the changes from https://github.com/benmosher/eslint-plugin-import/commit/8d7ec179c2ba2672d4d06200166ab64e1821527c

See https://unpkg.com/browse/eslint-plugin-import@2.23.1/CHANGELOG.md and https://unpkg.com/browse/eslint-plugin-import@2.23.1/lib/rules/newline-after-import.js

**Comment by ljharb** [comment]
@targos whoops, thanks. That will be tracked in #2077 and resolved shortly.
