### ISSUE TITLE
import/order crashes for typescript files, if no package.json file exists since version 2.23

### ISSUE THREAD

**Issue by g1thuser** [benmosher/eslint-plugin-import#2110]
While verifying a typescript file, the exception below is thrown for the import/order rule, if no package.json file exists. There is no such problem with version 2.22

Oops! Something went wrong! :(

ESLint: 7.27.0

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at dirname (node:path:1172:5)
    at getFilePackagePath (/home/jpalm/webdev/3rdpartylibs/node/node_modules/eslint-plugin-import/lib/core/packagePath.js:15:558)
    at getContextPackagePath (/home/jpalm/webdev/3rdpartylibs/node/node_modules/eslint-plugin-import/lib/core/packagePath.js:15:383)
    at typeTest (/home/jpalm/webdev/3rdpartylibs/node/node_modules/eslint-plugin-import/lib/core/importType.js:109:2291)
    at resolveImportType (/home/jpalm/webdev/3rdpartylibs/node/node_modules/eslint-plugin-import/lib/core/importType.js:109:2724)
    at computeRank (/home/jpalm/webdev/3rdpartylibs/node/node_modules/eslint-plugin-import/lib/rules/order.js:319:40)
    at registerNode (/home/jpalm/webdev/3rdpartylibs/node/node_modules/eslint-plugin-import/lib/rules/order.js:335:16)
    at handleImports (/home/jpalm/webdev/3rdpartylibs/node/node_modules/eslint-plugin-import/lib/rules/order.js:617:11)

**Comment by g1thuser** [comment]
Oops, I just saw now that there is already this issue here: https://github.com/benmosher/eslint-plugin-import/issues/2096
