### ISSUE TITLE
no-named-as-default-member throws an error for destructuring in for-of statements

### ISSUE THREAD

**Issue by lemonmade** [benmosher/eslint-plugin-import#249]
Given the following ESLint config:

```json
{
  "parser": "babel-eslint",

  "env": {
    "es6": true
  },

  "plugins": [
    "import"
  ],

  "rules": {
    "import/no-named-as-default-member": "error"
  }
}
```

and the following code:

```js
for (const {foo, bar} of baz) {}
```

the following error is thrown:

```
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at EventEmitter.handleDestructuringAssignment (/Users/chris/Projects/foo/node_modules/eslint-plugin-import/lib/rules/no-named-as-default-member.js:64:70)
    at emitOne (events.js:90:13)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/chris/Projects/foo/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/Users/chris/Projects/foo/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:609:23)
    at CommentEventGenerator.enterNode (/Users/chris/Projects/foo/node_modules/eslint/lib/util/comment-event-generator.js:99:23)
    at Controller.traverser.traverse.enter (/Users/chris/Projects/foo/node_modules/eslint/lib/eslint.js:887:36)
    at Controller.__execute (/Users/chris/Projects/foo/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/chris/Projects/foo/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/chris/Projects/foo/node_modules/eslint/lib/util/traverser.js:38:33)
```

The problem appears to here: https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-named-as-default-member.js#L53, where it's assumed that every declarator has an `init` (`for-of` declarators have `init = null`).

Thanks for the awesome ESLint plugin!

**Comment by benmosher** [comment]
Ah, yep. There are always these weird bugs when a rule is young. Thanks for the tip.
