### ISSUE TITLE
no-reassign rule fails

### ISSUE THREAD

**Issue by chase** [benmosher/eslint-plugin-import#29]
```
~/project/node_modules/eslint-plugin-import/lib/rules/no-reassign.js:15
    if (locals.has(id.name)) context.report(id, message(id.name))
                     ^
TypeError: Cannot read property 'name' of null
    at checkIdentifier (~/project/node_modules/eslint-plugin-import/lib/rules/no-reassign.js:15:22)
    at EventEmitter.FunctionDeclaration (~/project/node_modules/eslint-plugin-import/lib/rules/no-reassign.js:53:7)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (~/project/node_modules/eslint/lib/eslint.js:725:25)
    at Controller.__execute (~/project/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (~/project/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (~/project/node_modules/eslint/lib/eslint.js:718:24)
    at verify (~/project/node_modules/gulp-eslint/index.js:21:25)
    at DestroyableTransform._transform (~/project/node_modules/gulp-eslint/index.js:44:18)
    at DestroyableTransform.Transform._read (~/project/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
```

**Comment by benmosher** [comment]
Could you provide the linted code file, or a simplified test case that produces this exception?

I'd like to better understand what is happening before I start slinging code. 😅

**Comment by benmosher** [comment]
No worries, found a case that caused it (unnamed function as default export). Fixed. Will release ASAP.

**Comment by chase** [comment]
Thank you! I apologize for not expanding on it.
