### ISSUE TITLE
Handle ignored files when re-exporting from file

### ISSUE THREAD

**Issue by SohKai** [benmosher/eslint-plugin-import#348]
Currently, ignored files return `null` when you try to get an import from them (see [getExports#L79](https://github.com/benmosher/eslint-plugin-import/blob/master/src/core/getExports.js#L79)). However, this causes the `import/export` rule to throw an exception when you try to re-export everything from a file who is re-exporting from an ignored file, because ExportMap's `forEach` expects each of its re-exports to be able to get their imports (see [getExports#L331](https://github.com/benmosher/eslint-plugin-import/blob/master/src/core/getExports.js#L331)).

For example, running ESLint with `import/exports` turned on throws on these files:

```js
// test.js
export { default as x } from 'your-package'; // your-package is in the ignored settings (eg. in node_modules)

// reexport.js
export * from './test';
```

Exception:

```js
Cannot read property 'get' of null
TypeError: Cannot read property 'get' of null
    at .../node_modules/eslint-plugin-import/lib/core/getExports.js:422:48
    at Map.forEach (native)
    at ExportMap.forEach (.../node_modules/eslint-plugin-import/lib/core/getExports.js:419:20)
    at EventEmitter.ExportAllDeclaration (.../node_modules/eslint-plugin-import/lib/rules/export.js:82:21)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (.../node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (.../node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (.../node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (.../node_modules/eslint/lib/eslint.js:886:36)
```

---

It seems like the simplest thing to fix this would be to just check that `getImport()` exists before trying to use `.get()` on it (although I'm not really sure what the first argument to the callback represents -- would `null` as a possibility make sense there?), but from a cursory glance, I also feel that using `null` to represent ignored files seems somewhat brittle?

**Comment by igrayson** [comment]
I came across something that manifested slightly differently, but sounds related. Let me know, and I can open a new issue.

Symptom:
```javascript
Cannot read property 'size' of null
TypeError: Cannot read property 'size' of null
    at /Users/ian/workspace/eslint-export-all/node_modules/eslint-plugin-import/lib/core/getExports.js:463:29
    at Map.forEach (native)
    at ExportMap.get (/Users/ian/workspace/eslint-export-all/node_modules/eslint-plugin-import/lib/core/getExports.js:462:25)
    at processBodyStatement (/Users/ian/workspace/eslint-export-all/node_modules/eslint-plugin-import/lib/rules/namespace.js:66:27)
    at Array.forEach (native)
    at EventEmitter.Program (/Users/ian/workspace/eslint-export-all/node_modules/eslint-plugin-import/lib/rules/namespace.js:84:12)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/ian/workspace/eslint-export-all/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/ian/workspace/eslint-export-all/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
```

This happens when applying the `import/namespace` rule on:

test.js:
```
import * as foo from './foo';
```

foo.js:
```
export * from './bar';
```

bar.js:
```
module.exports = { };
```

* `bar.js` must be ignored.
* `bar.js` must use `module.exports` syntax.

It could be that [`hasExports`](https://github.com/benmosher/eslint-plugin-import/blob/master/src/core/getExports.js#L23) is failing to detect the fact that `module.exports` is a valid export statement; or that this apparatus as a whole is not prepared to deal with the old-fashioned `module.exports` style?

Test repo to reproduce: https://github.com/igrayson/eslint-export-all
`npm install && npm test`.

**Comment by benmosher** [comment]
@igrayson: sounds like the same issue. 

FWIW, it won't recognize module.exports as a namespace, but it definitely shouldn't throw an exception.
