### ISSUE TITLE
Error using eslint-plugin-import with SublimeText

### ISSUE THREAD

**Issue by doctyper** [benmosher/eslint-plugin-import#41]
I'm seeing an error in the SublimeText console when running `0.7.5`:

```
SublimeLinter: eslint: Example.jsx ['node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
Error while loading rule 'import/export': Set is not defined
ReferenceError: Error while loading rule 'import/export': Set is not defined
    at exports.default (node_modules/eslint-plugin-import/lib/rules/export.js:16:22)
    at node_modules/eslint/lib/eslint.js:628:32
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (node_modules/eslint/lib/eslint.js:619:16)
    at processText (node_modules/eslint/lib/cli-engine.js:201:27)
    at CLIEngine.executeOnText (node_modules/eslint/lib/cli-engine.js:361:26)
    at Object.cli.execute (node_modules/eslint/lib/cli.js:179:36)
    at configInit.initializeConfig.exitCode (node_modules/eslint/bin/eslint.js:13:28)
    at ConcatStream.<anonymous> (node_modules/eslint/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.EventEmitter.emit (events.js:117:20) 
```

For reference, we use `Set` in [nfl/react-helmet](https://github.com/nfl/react-helmet), and include a [shim](https://github.com/nfl/react-helmet/blob/master/src/index.jsx#L1) to polyfill them.

**Comment by benmosher** [comment]
Ah, yeah, that's on me. I neglected to explicitly import a `Set` polyfill into the rule definition. Consequence of the transition to full (Babel) ES6 for the rule source code...

Gimme an hour or so :sweat_smile:

**Comment by doctyper** [comment]
👌

**Comment by benmosher** [comment]
just pushed 0.7.6. I'll let you close this once you've confirmed it? I'm using io.js as my Node env (which has Map available as a native global), which is why I didn't see it.

**Comment by doctyper** [comment]
Lucky you! Testing now...

**Comment by doctyper** [comment]
New error:

```bash
SublimeLinter: eslint: Example.jsx ['node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
Object [object Object] has no method 'find'
TypeError: Object [object Object] has no method 'find'
    at checkDefault (node_modules/eslint-plugin-import/lib/rules/default.js:12:44)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (node_modules/eslint/lib/eslint.js:724:25)
    at Controller.__execute (node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (node_modules/eslint/lib/eslint.js:717:24)
    at processText (node_modules/eslint/lib/cli-engine.js:201:27)
    at CLIEngine.executeOnText (node_modules/eslint/lib/cli-engine.js:361:26)
    at Object.cli.execute (node_modules/eslint/lib/cli.js:179:36)
    at configInit.initializeConfig.exitCode (node_modules/eslint/bin/eslint.js:13:28) 
```

**Comment by benmosher** [comment]
Hmmmm... I had wondered as much. Babel is not polyfilling the ES6 Array methods... let me look into it.

**Comment by doctyper** [comment]
`core-js` does: https://github.com/zloirock/core-js/blob/master/shim.js#L51

Babel uses core-js as its polyfill but I guess it doesn't include all the shims?

**Comment by benmosher** [comment]
Well, I'm not including the polyfill because it will polyfill the whole ESLint process, AFAIK. Which feels weird to do from a plugin.

I'm only using one method in one place. I patched it to use `Array#some` instead, will be pushing momentarily.

**Comment by benmosher** [comment]
republished under 0.7.7. (tried to paste over 0.7.6... no dice. lost forever to the void)

**Comment by doctyper** [comment]
No more errors! Working as expected. Thanks @benmosher.

**Comment by benmosher** [comment]
:sunglasses: 

Just wrote up #43 to prevent this sort of thing in the future. No good having Travis run tests against 0.10 if the polyfill is present during test execution.
