### ISSUE TITLE
Cannot read property 'namespace' of undefined

### ISSUE THREAD

**Issue by CarlosAmaral** [benmosher/eslint-plugin-import#416]
TypeError: Cannot read property 'namespace' of undefined from `eslint-plugin-import/lib/rules/namespace.js`

Getting this error and not exactly sure why. Thanks.

**Comment by benmosher** [comment]
Are you running 1.10.1? I think I totally botched the publish and accidentally packaged the build products for v2.

**Comment by CarlosAmaral** [comment]
@benmosher Yes I am

**Comment by CarlosAmaral** [comment]
Thanks. Just tried, the error persists.
```
Cannot read property 'namespace' of undefined
TypeError: Cannot read property 'namespace' of undefined
    at EventEmitter.MemberExpression (/Users/carlosamaral/Documents/www/romanticism-react/node_modules/eslint-plugin-import/lib/rules/namespace.js:132:61)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/carlosamaral/Documents/www/romanticism-react/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/carlosamaral/Documents/www/romanticism-react/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/carlosamaral/Documents/www/romanticism-react/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/Users/carlosamaral/Documents/www/romanticism-react/node_modules/eslint/lib/eslint.js:905:36)
    at Controller.__execute (/Users/carlosamaral/Documents/www/romanticism-react/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/carlosamaral/Documents/www/romanticism-react/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/carlosamaral/Documents/www/romanticism-react/node_modules/eslint/lib/util/traverser.js:36:33)
```

**Comment by benmosher** [comment]
Hmm, tough to say without more info. Looks like a legitimate bug.

Can you isolate to specific lines of code and post them?

**Comment by CarlosAmaral** [comment]
Might reside here but I'm not sure. Let me know.
https://gist.github.com/anonymous/197ac98462ce78087136f3262dc91068

**Comment by benmosher** [comment]
Hmm, if any of them, probably one of these `let`s:

```js
import * as ReactMDL from 'react-mdl';
let Navigation = ReactMDL.Navigation;
let Drawer = ReactMDL.Drawer;
let Layout = ReactMDL.Layout;
let Content = ReactMDL.Content;
let Header = ReactMDL.Content;
```

Can you try commenting them and see if it goes away?

**Comment by CarlosAmaral** [comment]
You're correct. The error is gone. Thanks. What I should use instead? const?

**Comment by benmosher** [comment]
It's definitely a bug in the rule. It shouldn't do anything in these lines, much less throw an exception. I will try to fix ASAP.

In the meantime, 

```js

import {
  Navigation,
  Drawer,
  Layout,
  Content,
  Header,
} from 'react-mdl'
```
is roughly equivalent, and hopefully doesn't throw any errors. 😳

**Comment by CarlosAmaral** [comment]
Thanks bro.

**Comment by CarlosAmaral** [comment]
PS: I got these errors, not entirely sure if they're related, but the imports are working though.
```
!  3:27  '/Users/carlosamaral/Documents/www/romanticism-react/node_modules/react-mdl/src/index.js' imported multiple times                                                                         import/no-duplicates
  ✖  4:9   Navigation not found via ../../../node_modules/react-mdl/src/index.js -> ../../../node_modules/react-mdl/src/Layout/index.js -> ../../../node_modules/react-mdl/src/Layout/Navigation.js  import/named
  ✖  4:21  Drawer not found via ../../../node_modules/react-mdl/src/index.js -> ../../../node_modules/react-mdl/src/Layout/index.js -> ../../../node_modules/react-mdl/src/Layout/Drawer.js          import/named
  ✖  4:29  Layout not found via ../../../node_modules/react-mdl/src/index.js -> ../../../node_modules/react-mdl/src/Layout/index.js -> ../../../node_modules/react-mdl/src/Layout/Layout.js          import/named
  ✖  4:37  Content not found via ../../../node_modules/react-mdl/src/index.js -> ../../../node_modules/react-mdl/src/Layout/index.js -> ../../../node_modules/react-mdl/src/Layout/Content.js        import/named
  ✖  4:46  Header not found via ../../../node_modules/react-mdl/src/index.js -> ../../../node_modules/react-mdl/src/Layout/index.js -> ../../../node_modules/react-mdl/src/Layout/Header.js          import/named
  !  4:59  '/Users/carlosamaral/Documents/www/romanticism-react/node_modules/react-mdl/src/index.js' imported multiple times                                                                         import/no-duplicates
```

**Comment by benmosher** [comment]
Probably are related. Thanks!

**Comment by benmosher** [comment]
Did some digging. Turns out it's because the ES6 behind `react-mdl` is using object-spread, and ESLint doesn't handle it by default.

Not sure how to resolve. I probably need to handle somehow in the plugin, short-term. You can use these  settings in your `eslintrc` to resolve for now:

```js
{
  parserOptions: {
    sourceType: 'module',
    ecmaVersion: 6,
    ecmaFeatures: { experimentalObjectRestSpread: true, jsx: true }
  }
}
```

**Comment by CarlosAmaral** [comment]
@benmosher It did the trick. Thanks!

**Comment by ljharb** [comment]
This seems long since resolved.
