### ISSUE TITLE
Problem with using object rest and re-exports when rule `import/namespace` enabled

### ISSUE THREAD

**Issue by preco21** [benmosher/eslint-plugin-import#656]
Hello, I have some issue with re-exports.

I use `babel-eslint` parser for some experimental features. And I have used `object rest` operator for destructuring module. But `re-export` (in `index.js`) and `object rest` operator seems causes some issue with `import/namespace` rule.

When I enable  `import/namespace` rule, then create few files below, after that run lint, it causes error:

```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at testKey (C:\Workspace\sandbox\node_modules\eslint-plugin-import\lib\rules\namespace.js:166:29)
    at EventEmitter.VariableDeclarator (C:\Workspace\sandbox\node_modules\eslint-plugin-import\lib\rules\namespace.js:188:9)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (C:\Workspace\sandbox\node_modules\eslint\lib\util\node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (C:\Workspace\sandbox\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (C:\Workspace\sandbox\node_modules\eslint\lib\util\comment-event-generator.js:97:23)
    at Controller.enter (C:\Workspace\sandbox\node_modules\eslint\lib\eslint.js:927:36)
    at Controller.__execute (C:\Workspace\sandbox\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (C:\Workspace\sandbox\node_modules\estraverse\estraverse.js:501:28)
```

`.eslintrc.yml`:

```yml
root: true
parser: babel-eslint
plugins:
  - import
parserOptions:
  ecmaVersion: 2017
  sourceType: module
rules:
  import/namespace: error
```

`index.js`:

```javascript
export * from './module'; // re-exports
```

`module.js`:

```javascript
function foo() {
  
}

function bar() {
  
}

function baz() {
  
}

export {
  foo,
  bar,
  baz,
};
```

`test/spec.js`:

```javascript
import * as module from '..';

const {foo, ...moduleRest} = module; // when I comment this line, it works fine

...
```

Modules:

* `babel-eslint@7.1.0`
* `eslint@3.9.1`
* `eslint-plugin-import@2.1.0`
* `eslint-plugin-babel@3.3.0`

**Comment by evan-scott-zocdoc** [comment]
Seeing this too:

```
import * as lib from '../';

const {default, ...funcs} = lib;
```

Same error, with `import/namespaces` turned on. Commenting out the destructuring fixes it.

Using latest `babel-eslint`
