### ISSUE TITLE
Cannot find module './rules/no-unresolved'

### ISSUE THREAD

**Issue by nenti** [benmosher/eslint-plugin-import#820]
```
Cannot find module './rules/no-unresolved'
```
This error started to popup a couple of days ago without any noticeable change in my setup. 
``` eslint.rc
extends": "airbnb",
"plugins": [
   "import"
],
"settings": {
  "import/resolver": {
    "babel-module": {}
  }
},
"rules": {
  "import/no-unresolved": 2,
},
```
```
eslint-plugin-import": "^2.2.0",
```
Is anyone else experiencing this issue or can point me to a solution.
``` Error output:
Error: Cannot find module './rules/no-unresolved'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\piust\Documents\app\node_modules\eslint-plugin-import\lib\index.js:7:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by nenti** [comment]
I fixed this by removing the `esling-plugin-import` folder from my `node_modules` folder and running `npm-install`. The entire rules folder was missing and I havn't touched it.

**Comment by ljharb** [comment]
I've seen this happen occasionally when Dropbox (or another remote syncing tool) runs over my node_modules, fwiw.
